import type { Competition } from '@/types/competition';

export const MOCK_COMPETITIONS: Competition[] = [
  {
    id: 'comp-1',
    title: 'Gemastik XVIII - Divisi Pengembangan Aplikasi',
    slug: 'gemastik-xviii-pengembangan-aplikasi',
    organizer: 'Kemendikbudristek RI',
    description:
      'Kompetisi mahasiswa nasional di bidang aplikasi digital untuk menyelesaikan masalah nyata masyarakat.',
    category: 'Software Development',
    level: 'Nasional',
    registrationDeadline: '2026-10-15T23:59:00+08:00',
    competitionDate: '2026-11-20T09:00:00+08:00',
    registrationUrl: 'https://gemastik.kemdikbud.go.id/register',
    guidebookUrl: 'https://gemastik.kemdikbud.go.id/guidebook.pdf',
    poster: '/images/img/foto-1.webp',
    teamSize: '2-3 orang',
    eligibility: 'Mahasiswa aktif S1/D4 seluruh Indonesia',
    status: 'OPEN',
    featured: true,
    createdAt: '2026-09-01T08:00:00+08:00',
    updatedAt: '2026-09-20T10:00:00+08:00',
  },
  {
    id: 'comp-2',
    title: 'UNKLAB Hackathon 2026',
    slug: 'unklab-hackathon-2026',
    organizer: 'UVICS x Fakultas Ilmu Komputer',
    description:
      'Hackathon internal 24 jam untuk mahasiswa Unklab dengan tema smart campus.',
    category: 'Hackathon',
    level: 'Internal',
    registrationDeadline: '2026-10-05T23:59:00+08:00',
    competitionDate: '2026-10-18T08:00:00+08:00',
    registrationUrl: 'https://uvics.org/register/hackathon-2026',
    guidebookUrl: null,
    poster: '/images/img/foto-2.webp',
    teamSize: '3-4 orang',
    eligibility: 'Mahasiswa aktif Universitas Klabat',
    status: 'OPEN',
    featured: true,
    createdAt: '2026-08-15T08:00:00+08:00',
    updatedAt: '2026-09-18T09:30:00+08:00',
  },
  {
    id: 'comp-3',
    title: 'ASEAN Data Science Explorers',
    slug: 'asean-data-science-explorers',
    organizer: 'ASEAN Foundation & SAP',
    description:
      'Kompetisi data science tingkat Asia Tenggara yang berfokus pada isu-isu keberlanjutan.',
    category: 'Data Science',
    level: 'Internasional',
    registrationDeadline: '2026-09-30T23:59:00+07:00',
    competitionDate: '2026-12-05T09:00:00+07:00',
    registrationUrl: 'https://asdxchallenge.sap.com',
    guidebookUrl: 'https://asdxchallenge.sap.com/guidebook.pdf',
    poster: '/images/img/foto-3.webp',
    teamSize: '1-2 orang',
    eligibility: 'Mahasiswa aktif usia 15-25 tahun di negara ASEAN',
    status: 'UPCOMING',
    featured: false,
    createdAt: '2026-07-10T08:00:00+07:00',
    updatedAt: '2026-09-10T11:00:00+07:00',
  },
  {
    id: 'comp-4',
    title: 'Kompetisi Cyber Security Nasional 2026',
    slug: 'kompetisi-cyber-security-nasional-2026',
    organizer: 'BSSN & ID-SIRTII',
    description:
      'Ajang capture the flag (CTF) nasional untuk mengasah kemampuan keamanan siber mahasiswa.',
    category: 'Cyber Security',
    level: 'Nasional',
    registrationDeadline: '2026-08-20T23:59:00+07:00',
    competitionDate: '2026-09-10T08:00:00+07:00',
    registrationUrl: null,
    guidebookUrl: 'https://bssn.go.id/ctf/guidebook.pdf',
    poster: '/images/img/foto-4.webp',
    teamSize: '3 orang',
    eligibility: 'Mahasiswa aktif S1 seluruh Indonesia',
    status: 'ONGOING',
    featured: false,
    createdAt: '2026-06-01T08:00:00+07:00',
    updatedAt: '2026-09-11T08:00:00+07:00',
  },
  {
    id: 'comp-5',
    title: 'Indonesia UI/UX Design Championship 2025',
    slug: 'indonesia-uiux-design-championship-2025',
    organizer: 'IDEA (Indonesia Design Entrepreneur Association)',
    description:
      'Kompetisi desain UI/UX nasional untuk mahasiswa dengan studi kasus produk digital.',
    category: 'UI/UX Design',
    level: 'Nasional',
    registrationDeadline: '2025-11-01T23:59:00+07:00',
    competitionDate: '2025-12-15T09:00:00+07:00',
    registrationUrl: 'https://idea.or.id/register',
    guidebookUrl: 'https://idea.or.id/guidebook.pdf',
    poster: '/images/img/foto-5.webp',
    teamSize: '1 orang',
    eligibility: 'Mahasiswa aktif seluruh Indonesia',
    status: 'FINISHED',
    featured: false,
    createdAt: '2025-09-01T08:00:00+07:00',
    updatedAt: '2025-12-16T08:00:00+07:00',
  },
  {
    id: 'comp-6',
    title: 'Lomba Karya Tulis Ilmiah Teknologi 2026',
    slug: 'lomba-karya-tulis-ilmiah-teknologi-2026',
    organizer: 'Dinas Pendidikan Sulawesi Utara',
    description:
      'Lomba karya tulis ilmiah dengan fokus inovasi teknologi untuk pembangunan daerah.',
    category: 'Karya Tulis Ilmiah',
    level: 'Internal',
    registrationDeadline: '2026-09-25T23:59:00+08:00',
    competitionDate: '2026-10-01T09:00:00+08:00',
    registrationUrl: 'https://dispendik-sulut.go.id/lkti',
    guidebookUrl: null,
    poster: null,
    teamSize: null,
    eligibility: null,
    status: 'CLOSED',
    featured: false,
    createdAt: '2026-08-01T08:00:00+08:00',
    updatedAt: '2026-09-26T08:00:00+08:00',
  },
  {
    id: 'comp-gemastik-2026',
    slug: 'gemastik-xviii-2026',
    title: 'GEMASTIK XVIII: Divisi Software Development & UX Design',
    organizer: 'Puspresnas Kemdikbudristek RI',
    description:
      'Kompetisi teknologi informasi dan komunikasi nasional paling bergengsi antar perguruan tinggi se-Indonesia untuk menguji inovasi perangkat lunak dan keunggulan desain antarmuka.',
    category: 'Software Engineering',
    level: 'Nasional',
    registrationDeadline: '2026-11-15T23:59:00+08:00',
    competitionDate: '2026-12-10T09:00:00+08:00',
    registrationUrl: 'https://gemastik.kemdikbud.go.id',
    guidebookUrl: 'https://gemastik.kemdikbud.go.id/guidebook',
    poster: '/images/img/foto-1.webp',
    teamSize: '3 Orang / Tim',
    eligibility: 'Mahasiswa Aktif S1/D4 Seluruh Indonesia',
    status: 'OPEN',
    featured: false,
    createdAt: '2026-09-01T08:00:00+08:00',
    updatedAt: '2026-09-20T10:00:00+08:00',
  },
  {
    id: 'comp-icpc-jakarta-2026',
    slug: 'icpc-asia-jakarta-regional-2026',
    title: 'The 2026 ICPC Asia Jakarta Regional Contest',
    organizer: 'ICPC Foundation & Universitas Bina Nusantara',
    description:
      'Kontes pemrograman kompetitif internasional tingkat regional Asia untuk menguji kecepatan logika matematika, perancangan algoritma lanjut, dan ketahanan problem solving beregu.',
    category: 'Competitive Programming',
    level: 'Internasional',
    registrationDeadline: '2026-10-28T23:59:00+08:00',
    competitionDate: '2026-11-21T09:00:00+08:00',
    registrationUrl: 'https://icpc.global',
    guidebookUrl: 'https://icpc.global/regionals/rules',
    poster: '/images/img/foto-10.webp',
    teamSize: '3 Orang / Tim',
    eligibility: 'Mahasiswa Terdaftar Resmi (Eligibility Rules ICPC)',
    status: 'OPEN',
    featured: false,
    createdAt: '2026-08-10T08:00:00+08:00',
    updatedAt: '2026-09-22T10:00:00+08:00',
  },
  {
    id: 'comp-hackathon-merdeka-2026',
    slug: 'hackathon-merdeka-nusantara',
    title: 'Nusantara AI & Web3 Innovation Hackathon',
    organizer: 'Kementerian Komunikasi dan Informatika RI',
    description:
      'Ajang hackathon 48 jam nonstop merancang aplikasi berbasis Artificial Intelligence untuk akselerasi smart city dan layanan publik digital di Indonesia.',
    category: 'Hackathon',
    level: 'Nasional',
    registrationDeadline: '2026-11-05T23:59:00+08:00',
    competitionDate: '2026-11-18T09:00:00+08:00',
    registrationUrl: 'https://kominfo.go.id/hackathon',
    guidebookUrl: 'https://kominfo.go.id/guidebook-2026.pdf',
    poster: '/images/img/foto-11.webp',
    teamSize: '2 - 4 Orang / Tim',
    eligibility: 'Mahasiswa & Talenta Muda < 25 Tahun',
    status: 'OPEN',
    featured: false,
    createdAt: '2026-09-05T08:00:00+08:00',
    updatedAt: '2026-09-25T10:00:00+08:00',
  },
  {
    id: 'comp-findit-uiux-2026',
    slug: 'find-it-ui-ux-competition',
    title: 'FIND IT! National UI/UX Design Challenge',
    organizer: 'DTETI Universitas Gadjah Mada',
    description:
      'Perlombaan perancangan user experience dan UI interaktif memecahkan problematika aksesibilitas produk teknologi finansial dan inklusif di Indonesia.',
    category: 'UI/UX Design',
    level: 'Nasional',
    registrationDeadline: '2026-10-20T23:59:00+08:00',
    competitionDate: '2026-11-05T09:00:00+08:00',
    registrationUrl: 'https://find-it.id',
    guidebookUrl: 'https://find-it.id/guidebook',
    poster: '/images/img/foto-4.webp',
    teamSize: '2 - 3 Orang / Tim',
    eligibility: 'Mahasiswa D3/D4/S1 Aktif',
    status: 'OPEN',
    featured: false,
    createdAt: '2026-08-20T08:00:00+08:00',
    updatedAt: '2026-09-15T10:00:00+08:00',
  },
  {
    id: 'comp-compfest-ds-2026',
    slug: 'compfest-data-science-academy',
    title: 'COMPFEST: National Data Science Challenge',
    organizer: 'Fasilkom Universitas Indonesia',
    description:
      'Tantangan analisis big data, machine learning modeling, and insight visualization untuk optimasi supply chain berkelanjutan.',
    category: 'Data Science',
    level: 'Nasional',
    registrationDeadline: '2026-10-01T23:59:00+08:00',
    competitionDate: '2026-10-15T09:00:00+08:00',
    registrationUrl: 'https://compfest.id',
    guidebookUrl: null,
    poster: '/images/img/foto-7.webp',
    teamSize: '3 Orang / Tim',
    eligibility: 'Mahasiswa Aktif Seluruh Indonesia',
    status: 'CLOSED',
    featured: false,
    createdAt: '2026-07-25T08:00:00+08:00',
    updatedAt: '2026-09-20T10:00:00+08:00',
  },
  {
    id: 'comp-joints-algo-2026',
    slug: 'joints-competitive-programming',
    title: 'JOINTS Programming Contest 2026',
    organizer: 'Universitas Gadjah Mada',
    description:
      'Lomba competitive programming perorangan dengan standar ICPC untuk menguji efisiensi algoritma graf, dynamic programming, dan teori bilangan.',
    category: 'Competitive Programming',
    level: 'Nasional',
    registrationDeadline: '2026-11-25T23:59:00+08:00',
    competitionDate: '2026-12-08T09:00:00+08:00',
    registrationUrl: 'https://joints.id',
    guidebookUrl: null,
    poster: '/images/img/foto-8.webp',
    teamSize: 'Individu (1 Orang)',
    eligibility: 'Mahasiswa Aktif',
    status: 'UPCOMING',
    featured: false,
    createdAt: '2026-09-01T08:00:00+08:00',
    updatedAt: '2026-09-18T10:00:00+08:00',
  },
];
